---
title: ''
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages

```{r}
library(tidyverse)
library(scales) 
library(ggpubr)
library(forcats)
```

## data

```{r}
bok_survey_data <-read.csv("/Users/kenjinchang/github/billie-venue-surveys/data/bok-survey-data.csv")
```

## cleaning

```{r}
bok_survey_data <- bok_survey_data %>%
  mutate(pb_item_again=case_when(pb_item_again=="Yes"~1,
                   pb_item_again=="No"~0)) %>%
  mutate(satisfaction_rating=case_when(satisfaction_rating=="I did not try a plant-based menu item"~NA,
                                       satisfaction_rating=="1 (Very unsatisfied)"~1,
                                       satisfaction_rating=="2 (Unsatisfied)"~2,
                                       satisfaction_rating=="3 (Neutral)"~3,
                                       satisfaction_rating=="4 (Satisfied)"~4,
                                       satisfaction_rating=="5 (Very Satisfied)"~5))
```

## analysis

```{r}
bok_survey_data %>%
  drop_na() %>%
  filter(pb_item=="Yes"|pb_item=="No") %>%
  group_by(pb_item) %>%
  summarise(mean(satisfaction_rating))
```

```{r}
mean_satisfaction_rating_plot <- bok_survey_data %>%
  drop_na() %>%
  filter(pb_item=="Yes"|pb_item=="No") %>%
  group_by(pb_item) %>%
  summarise(mean_satisfaction_rating=mean(satisfaction_rating)) %>%
  ggplot(aes(x=pb_item,y=mean_satisfaction_rating)) +
  geom_col(fill="slateblue") +
  scale_x_discrete(labels=c("No (n=55)","Yes (n=48)")) +
  xlab("Tried Plant-Based Item") + 
  ylab("Mean Satisfaction Rating") +
  labs(title="Mean satisfaction rating between concertgoers who did and did not try a plant-based item",caption="N=103") +
  theme(panel.grid=element_blank(),panel.background=element_rect(fill="white"),panel.border=element_rect(fill=NA),legend.title=element_text(size=10),legend.text=element_text(size=10),plot.title=element_text(size=10)) 
mean_satisfaction_rating_plot
```

```{r}
bok_survey_data %>%
  drop_na() %>%
  filter(pb_item=="Yes"|pb_item=="No") %>%
  group_by(pb_item) %>%
  summarise(total_pb_item_again=sum(pb_item_again)) %>%
  mutate(total_pb_item_not_again=case_when(pb_item=="No"~55-total_pb_item_again,
                                            pb_item=="Yes"~48-total_pb_item_again)) %>%
  pivot_longer(!pb_item,names_to="pb_item_again",values_to="count") 
```

```{r}
total_pb_item_again_plot <- bok_survey_data %>%
  drop_na() %>%
  filter(pb_item=="Yes"|pb_item=="No") %>%
  group_by(pb_item) %>%
  summarise(total_pb_item_again=sum(pb_item_again)) %>%
  mutate(total_pb_item_not_again=case_when(pb_item=="No"~55-total_pb_item_again,
                                            pb_item=="Yes"~48-total_pb_item_again)) %>%
  pivot_longer(!pb_item,names_to="pb_item_again",values_to="count") %>%
  ggplot(aes(x=pb_item,y=count,fill=pb_item_again)) +
  geom_col(position="fill") +
  scale_fill_manual(values=c("slateblue","darkseagreen"),labels=c("Willing","Unwilling"),name="Willingness to Try a\nPlant-Based Item") +
  xlab("Tried Plant-Based Item") + 
  ylab("Proportion Willing to Try a Plant-Based Item") +
  labs(title="Proportion of concertgoers who would try a plant-based item at a future show",caption="N=103") +
  theme(panel.grid=element_blank(),panel.background=element_rect(fill="white"),panel.border=element_rect(fill=NA),legend.title=element_text(size=10),legend.text=element_text(size=10),plot.title=element_text(size=10)) 
total_pb_item_again_plot
```

```{r}
plot_array <- ggarrange(mean_satisfaction_rating_plot,total_pb_item_again_plot,
          labels=c("A","B"),
          ncol=2)
ggsave(filename="plot_array.png",plot=plot_array,path="/Users/kenjinchang/github/billie-venue-surveys/figures",width=36,height=16,units="cm",dpi=150,limitsize=TRUE)
```

